networks:
  internal_net:
    driver: bridge
    internal: true
  external_net:
    driver: bridge

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      - internal_net
      - external_net
    ports:
      # DNS Ports
      - "${DNS_PORT}:53/tcp"
      - "${DNS_PORT}:53/udp"
      # Default HTTP Port
      - "${WEB_PORT}:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "${HTTPS_PORT}:443/tcp"
      # Uncomment the below if using Pi-hole as your DHCP Server
      #- "67:67/udp"
      # Uncomment the line below if you are using Pi-hole as your NTP server
      #- "123:123/udp"
    environment:
      # Set the appropriate timezone for your location from
      # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones, e.g:
      TZ: 'Europe/Kiev'
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      FTLCONF_webserver_api_password: '${WEB_PASSWORD}'
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
      FTLCONF_dns_listeningMode: 'all'
      FTLCONF_dns_upstreams: 'unbound#5335'
      ADDITIONAL_PACKAGES: 'wget curl sqlite3 sqlite'
    # Volumes store your data between container upgrades
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - './pihole/etc:/etc/pihole'
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards. Needs environment variable FTLCONF_misc_etc_dnsmasq_d: 'true'
      - './pihole/dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      - NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      #- SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      #- SYS_NICE
    restart: unless-stopped
    
  unbound:
    container_name: unbound
    image: madnuttah/unbound
    networks:
      - internal_net
      - external_net
    environment:
      TZ: "Europe/Kiev"
    volumes:
      - ./unbound/unbound.conf:/etc/unbound/unbound.conf:rw
      - ./unbound/conf.d/:/usr/local/unbound/conf.d/:rw
      #- ./log.d/unbound.log:/usr/local/unbound/log.d/unbound.log:rw
      - ./unbound/zones.d/:/usr/local/unbound/zones.d/:rw
    healthcheck:
     test: /usr/local/unbound/sbin/healthcheck.sh
     interval: 60s
     retries: 5
     start_period: 15s
     timeout: 30s
      
    restart: unless-stopped
